build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    # CONAN_LOGIN_USERNAME, CONAN_PASSWORD and CONAN_UPLOAD must be set in Appveyor project's settings
    CONAN_USERNAME: "osechet"
    CONAN_CHANNEL: "testing"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_STABLE_BRANCH_PATTERN: "stable/*"

    matrix:
        # - MINGW_CONFIGURATIONS: '6@x86_64@seh@posix, 7@x86_64@seh@posix'
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86_64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Debug
          CONAN_ARCHS: x86_64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86_64
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug
          CONAN_ARCHS: x86_64
        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
        #   CONAN_VISUAL_VERSIONS: 16
        #   CONAN_BUILD_TYPES: Release
        #   CONAN_ARCHS: x86_64
        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
        #   CONAN_VISUAL_VERSIONS: 16
        #   CONAN_BUILD_TYPES: Debug
        #   CONAN_ARCHS: x86_64

install:
  - set PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
